### ISSUE TITLE
adapter doesn't work after update 0.5.9 to 0.6.1

### ISSUE THREAD

**Issue by dansiebert** [DrozmotiX/ioBroker.wled#270]
**!!! Before you start !!!**  
1. Verify if there is not already an issue requesting the same.
OK, checked.
2. Is this really a bug of current code, or an enhancement request ?
I think a bug.

**Describe the bug**  
The updated adapter doesn't start after update from 0.5.9 to 0.6.1.

**To Reproduce**  
1. Go to 'Adapters'
2. Click on 'Show only adapters with updates'
3. Update instralled WLED Adapter version 0.5.9 to 0.6.1
4. Updated adapter does not start and shows errors in the log.

**Expected behavior**  
The adapter starts up and works as usual.

**Screenshots & Logfiles**  
2021-09-08 14:49:06.890  - ESC[32minfoESC[39m: host.server-tieckow iobroker Update wled from @0.5.6 to @0.6.1
2021-09-08 14:49:07.176  - ESC[32minfoESC[39m: host.server-tieckow iobroker NPM version: 6.14.14
2021-09-08 14:49:07.178  - ESC[32minfoESC[39m: host.server-tieckow iobroker npm install iobroker.wled@0.6.1 --loglevel error --prefix "/opt/iobroker" (System call)
2021-09-08 14:49:37.233  - ESC[32minfoESC[39m: host.server-tieckow iobroker upload [6] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/words.js words.js application/javascript
2021-09-08 14:49:37.262  - ESC[32minfoESC[39m: host.server-tieckow iobroker Update "system.adapter.wled.0"
2021-09-08 14:49:37.277  - ESC[32minfoESC[39m: host.server-tieckow stopInstance system.adapter.wled.0 (force=false, process=true)
2021-09-08 14:49:37.320  - ESC[32minfoESC[39m: host.server-tieckow stopInstance system.adapter.wled.0 send kill signal
2021-09-08 14:49:37.370  - ESC[32minfoESC[39m: host.server-tieckow iobroker upload [5] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/wled_large.png wled_large.png image/png
2021-09-08 14:49:37.303  - ESC[32minfoESC[39m: wled.0 (8495) Got terminate signal TERMINATE_YOURSELF
2021-09-08 14:49:37.337  - ESC[32minfoESC[39m: wled.0 (8495) terminating
2021-09-08 14:49:37.343  - ESC[32minfoESC[39m: wled.0 (8495) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2021-09-08 14:49:37.344  - ESC[32minfoESC[39m: wled.0 (8495) cleaned everything up...
2021-09-08 14:49:37.424  - ESC[32minfoESC[39m: host.server-tieckow iobroker upload [4] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/wled.png wled.png image/png
2021-09-08 14:49:37.484  - ESC[32minfoESC[39m: host.server-tieckow iobroker upload [3] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/style.css style.css text/css
2021-09-08 14:49:37.544  - ESC[32minfoESC[39m: host.server-tieckow iobroker upload [2] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/index_m.html index_m.html text/html
2021-09-08 14:49:37.597  - ESC[32minfoESC[39m: host.server-tieckow iobroker upload [1] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/button.png button.png image/png
2021-09-08 14:49:37.652  - ESC[32minfoESC[39m: host.server-tieckow iobroker upload [0] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/admin.d.ts admin.d.ts video/mp2t
2021-09-08 14:49:37.706  - ESC[32minfoESC[39m: host.server-tieckow iobroker Adapter "wled" updated
2021-09-08 14:49:37.935  - ESC[32minfoESC[39m: host.server-tieckow instance system.adapter.wled.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2021-09-08 14:49:38.717  - ESC[32minfoESC[39m: host.server-tieckow iobroker exit 0
2021-09-08 14:49:40.398  - ESC[32minfoESC[39m: host.server-tieckow instance system.adapter.wled.0 started with pid 23006
2021-09-08 14:49:40.601  - ESC[31merrorESC[39m: host.server-tieckow Caught by controller[0]: internal/modules/cjs/loader.js:818
2021-09-08 14:49:40.601  - ESC[31merrorESC[39m: host.server-tieckow Caught by controller[0]:   throw err;
2021-09-08 14:49:40.601  - ESC[31merrorESC[39m: host.server-tieckow Caught by controller[0]:   ^
2021-09-08 14:49:40.601  - ESC[31merrorESC[39m: host.server-tieckow Caught by controller[0]: Error: Cannot find module 'axios'
2021-09-08 14:49:40.601  - ESC[31merrorESC[39m: host.server-tieckow Caught by controller[0]: Require stack:
2021-09-08 14:49:40.601  - ESC[31merrorESC[39m: host.server-tieckow Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.wled/main.js
2021-09-08 14:49:40.601  - ESC[31merrorESC[39m: host.server-tieckow Caught by controller[0]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
2021-09-08 14:49:40.601  - ESC[31merrorESC[39m: host.server-tieckow Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
2021-09-08 14:49:40.602  - ESC[31merrorESC[39m: host.server-tieckow Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:887:19)
2021-09-08 14:49:40.602  - ESC[31merrorESC[39m: host.server-tieckow Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:74:18)
2021-09-08 14:49:40.602  - ESC[31merrorESC[39m: host.server-tieckow Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.wled/main.js:15:26)
2021-09-08 14:49:40.602  - ESC[31merrorESC[39m: host.server-tieckow Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-09-08 14:49:40.602  - ESC[31merrorESC[39m: host.server-tieckow Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-09-08 14:49:40.602  - ESC[31merrorESC[39m: host.server-tieckow Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:863:32)
2021-09-08 14:49:40.602  - ESC[31merrorESC[39m: host.server-tieckow Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-09-08 14:49:40.602  - ESC[31merrorESC[39m: host.server-tieckow Caught by controller[0]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
2021-09-08 14:49:40.602  - ESC[31merrorESC[39m: host.server-tieckow Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
2021-09-08 14:49:40.602  - ESC[31merrorESC[39m: host.server-tieckow Caught by controller[0]:   requireStack: [ '/opt/iobroker/node_modules/iobroker.wled/main.js' ]
2021-09-08 14:49:40.602  - ESC[31merrorESC[39m: host.server-tieckow Caught by controller[0]: }
2021-09-08 14:49:40.602  - ESC[31merrorESC[39m: host.server-tieckow instance system.adapter.wled.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

**Versions:**  
 - Adapter version: 0.6.1
 - JS-Controller version: 3.3.15
 - Node version: v12.22.5
 - Operating system: Debian Linux 10.10 (linux-image-amd64    4.19+105+deb10u6)

**Additional context**

**Comment by DutchmanNL** [comment]
Hmm this looks like an issue related to NodeJS 12, I cannot reproduce this on NodeJS 14.
Will setup an test-environment to check out, here all looks normally after updating : 

<img width="1494" alt="Schermafbeelding 2021-09-08 om 16 21 28" src="https://user-images.githubusercontent.com/7318445/132527170-ac9841f5-f46f-4c34-9799-b04cce9df598.png">

<img width="1496" alt="Schermafbeelding 2021-09-08 om 16 21 50" src="https://user-images.githubusercontent.com/7318445/132527230-05ff4141-8491-402e-8f4a-23ebb8b17884.png">

**Comment by DutchmanNL** [comment]
@dansiebert can you please try version 0.6.0 instead of 0.6.1 ?

**Comment by guergen1** [comment]
V0.6.0 läuft, beim Udate auf 0.6.1 folgende Einträge im Log:
`
<html><body>


2021-09-08 18:29:12.362  - info: host.iobroker-slave instance system.adapter.wled.0 started with pid 1037
--
2021-09-08 18:29:12.798  - error: host.iobroker-slave Caught by controller[0]: internal/modules/cjs/loader.js:818
2021-09-08 18:29:12.798  - error: host.iobroker-slave Caught by controller[0]:   throw err;
2021-09-08 18:29:12.798  - error: host.iobroker-slave Caught by controller[0]:   ^
2021-09-08 18:29:12.799  - error: host.iobroker-slave Caught by controller[0]: Error: Cannot find module 'axios'
2021-09-08 18:29:12.799  - error: host.iobroker-slave Caught by controller[0]: Require stack:
2021-09-08 18:29:12.799  - error: host.iobroker-slave Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.wled/main.js
2021-09-08 18:29:12.799  - error: host.iobroker-slave Caught by controller[0]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
2021-09-08 18:29:12.799  - error: host.iobroker-slave Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
2021-09-08 18:29:12.799  - error: host.iobroker-slave Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:887:19)
2021-09-08 18:29:12.799  - error: host.iobroker-slave Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:74:18)
2021-09-08 18:29:12.800  - error: host.iobroker-slave Caught by controller[0]:     at Object. (/opt/iobroker/node_modules/iobroker.wled/main.js:15:26)
2021-09-08 18:29:12.800  - error: host.iobroker-slave Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-09-08 18:29:12.800  - error: host.iobroker-slave Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-09-08 18:29:12.800  - error: host.iobroker-slave Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:863:32)
2021-09-08 18:29:12.800  - error: host.iobroker-slave Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-09-08 18:29:12.800  - error:  host.iobroker-slave Caught by controller[0]:     at  Function.executeUserEntryPoint [as runMain]  (internal/modules/run_main.js:60:12) {
2021-09-08 18:29:12.801  - error: host.iobroker-slave Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
2021-09-08 18:29:12.801  - error: host.iobroker-slave Caught by controller[0]:   requireStack: [ '/opt/iobroker/node_modules/iobroker.wled/main.js' ]
2021-09-08 18:29:12.801  - error: host.iobroker-slave Caught by controller[0]: }
2021-09-08 18:29:12.801  - error: host.iobroker-slave instance system.adapter.wled.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2021-09-08 18:29:12.802  - info: host.iobroker-slave Restart adapter system.adapter.wled.0 because enabled


</body>
</html>`

**Comment by dansiebert** [comment]
I can confirm what guergen1 said. Version 0.6.0 is running, version 0.6.1 is not running.

2021-09-08 19:02:07.896  - info: wled.0 (18836) starting. Version 0.6.0 in /opt/iobroker/node_modules/iobroker.wled, node: v12.22.5, js-controller: 3.3.15
2021-09-08 19:02:07.920  - info: wled.0 (18836) Bonjour service started, new  devices  will  be detected automatically
2021-09-08 19:02:17.922  - info: wled.0 (18836) WLED initialisation finalized, ready to do my job have fun !
2021-09-08 19:02:18.081  - info: yeelight-2.0 (21200) State value to set for "yeelight-2.0.Kugellicht-WZ.control.active_bright" has to be type "number" but received type "string" 
2021-09-08 19:02:18.082  - info: yeelight-2.0 (21200) State value to set for "yeelight-2.0.Kugellicht-WZ.control.ct" has to be type "number" but received type "string" 
2021-09-08 19:02:48.085  - info: yeelight-2.0 (21200) State value to set for "yeelight-2.0.Kugellicht-WZ.control.active_bright" has to be type "number" but received type "string" 
2021-09-08 19:02:48.085  - info: yeelight-2.0 (21200) State value to set for "yeelight-2.0.Kugellicht-WZ.control.ct" has to be type "number" but received type "string" 
2021-09-08 19:02:56.109  - info: host.server-tieckow iobroker upgrade wled@0.6.1
2021-09-08 19:02:57.091  - info: host.server-tieckow iobroker Update wled from @0.6.0 to @0.6.1
2021-09-08 19:02:57.316  - info: host.server-tieckow iobroker NPM version: 6.14.14
2021-09-08 19:02:57.317  - info: host.server-tieckow iobroker npm install iobroker.wled@0.6.1 --loglevel error --prefix "/opt/iobroker" (System call)
2021-09-08 19:03:13.532  - info: sonoff.0 (19508) Client [gosund-timi-stehlampe] connection closed: closed
2021-09-08 19:03:14.062  - info: sonoff.0 (19508) Client [gosund-timi-stehlampe] connected with secret 1631120594060_6732
2021-09-08 19:03:18.089  - info: yeelight-2.0 (21200) State value to set for "yeelight-2.0.Kugellicht-WZ.control.active_bright" has to be type "number" but received type "string" 
2021-09-08 19:03:18.090  - info: yeelight-2.0 (21200) State value to set for "yeelight-2.0.Kugellicht-WZ.control.ct" has to be type "number" but received type "string" 
2021-09-08 19:03:25.998  - info: host.server-tieckow iobroker upload [6] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/words.js words.js application/javascript
2021-09-08 19:03:26.028  - info: host.server-tieckow iobroker Update "system.adapter.wled.0"
2021-09-08 19:03:26.042  - info: host.server-tieckow stopInstance system.adapter.wled.0 (force=false, process=true)
2021-09-08 19:03:26.044  - info: wled.0 (18836) Got terminate signal TERMINATE_YOURSELF
2021-09-08 19:03:26.044  - info: wled.0 (18836) cleaned everything up...
2021-09-08 19:03:26.044  - info: wled.0 (18836) terminating
2021-09-08 19:03:26.045  - info: wled.0 (18836) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2021-09-08 19:03:26.084  - info: host.server-tieckow stopInstance system.adapter.wled.0 send kill signal
2021-09-08 19:03:26.092  - info: host.server-tieckow iobroker upload [5] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/wled_large.png wled_large.png image/png
2021-09-08 19:03:26.146  - info: host.server-tieckow iobroker upload [4] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/wled.png wled.png image/png
2021-09-08 19:03:26.213  - info: host.server-tieckow iobroker upload [3] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/style.css style.css text/css
2021-09-08 19:03:26.266  - info: host.server-tieckow iobroker upload [2] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/index_m.html index_m.html text/html
2021-09-08 19:03:26.321  - info: host.server-tieckow iobroker upload [1] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/button.png button.png image/png
2021-09-08 19:03:26.375  - info: host.server-tieckow iobroker upload [0] wled.admin /opt/iobroker/node_modules/iobroker.wled/admin/admin.d.ts admin.d.ts video/mp2t
2021-09-08 19:03:26.430  - info: host.server-tieckow iobroker Adapter "wled" updated
2021-09-08 19:03:26.614  - info: host.server-tieckow instance system.adapter.wled.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2021-09-08 19:03:27.441  - info: host.server-tieckow iobroker exit 0
2021-09-08 19:03:29.148  - info: host.server-tieckow instance system.adapter.wled.0 started with pid 20121
2021-09-08 19:03:29.353  - error: host.server-tieckow Caught by controller[0]: internal/modules/cjs/loader.js:818
2021-09-08 19:03:29.353  - error: host.server-tieckow Caught by controller[0]:   throw err;
2021-09-08 19:03:29.353  - error: host.server-tieckow Caught by controller[0]:   ^
2021-09-08 19:03:29.353  - error: host.server-tieckow Caught by controller[0]: Error: Cannot find module 'axios'
2021-09-08 19:03:29.353  - error: host.server-tieckow Caught by controller[0]: Require stack:
2021-09-08 19:03:29.353  - error: host.server-tieckow Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.wled/main.js
2021-09-08 19:03:29.353  - error: host.server-tieckow Caught by controller[0]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
2021-09-08 19:03:29.353  - error: host.server-tieckow Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
2021-09-08 19:03:29.354  - error: host.server-tieckow Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:887:19)
2021-09-08 19:03:29.354  - error: host.server-tieckow Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:74:18)
2021-09-08 19:03:29.354  - error: host.server-tieckow Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.wled/main.js:15:26)
2021-09-08 19:03:29.354  - error: host.server-tieckow Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-09-08 19:03:29.354  - error: host.server-tieckow Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-09-08 19:03:29.354  - error: host.server-tieckow Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:863:32)
2021-09-08 19:03:29.354  - error: host.server-tieckow Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-09-08 19:03:29.354  - error: host.server-tieckow Caught by controller[0]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
2021-09-08 19:03:29.354  - error: host.server-tieckow Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
2021-09-08 19:03:29.354  - error: host.server-tieckow Caught by controller[0]:   requireStack: [ '/opt/iobroker/node_modules/iobroker.wled/main.js' ]
2021-09-08 19:03:29.354  - error: host.server-tieckow Caught by controller[0]: }
2021-09-08 19:03:29.355  - error: host.server-tieckow instance system.adapter.wled.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2021-09-08 19:03:29.355  - info: host.server-tieckow Restart adapter system.adapter.wled.0 because enabled

**Comment by DutchmanNL** [comment]
please test 0.6.2 https://github.com/DrozmotiX/ioBroker.wled/commit/5661b03fbc4576fa639cf0178f71905ebb5acda0
