### ISSUE TITLE
Adapter doesn't work

### ISSUE THREAD

**Issue by Dragon0501** [DrozmotiX/ioBroker.wled#290]
`

wled.0 | 2021-10-17 18:36:48.690 | error | Cannot read property 'error' of undefined
-- | -- | -- | --
wled.0 | 2021-10-17 18:36:48.689 | error | TypeError: Cannot read property 'error' of undefined at Wled.onUnload (/opt/iobroker/node_modules/iobroker.wled/main.js:130:13) at Wled.emit (events.js:314:20) at process.stop (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8747:22) at Object.onceWrapper (events.js:421:26) at process.emit (events.js:314:20) at process.exit (internal/process/per_thread.js:168:15) at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:352:25) at processTicksAndRejections (internal/process/task_queues.js:97:5)
wled.0 | 2021-10-17 18:36:48.687 | error | unhandled promise rejection: Cannot read property 'error' of undefined
wled.0 | 2021-10-17 18:36:48.687 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch()

`

LXC on Proxmox...
What is the Problem?

**Comment by Dragon0501** [comment]
Problem solved by building a new virtual system. The LXC just made problems. So reactivating an VM solved it.
